#!/bin/sh
# Description: startx wrapper, loads settings and WM/DE.
# Mostly from lightdm: /etc/lightdm/Xsession
# TODO: collect errors with: startx 2> ~/.xsession-errors

export XDG_SESSION_TYPE="x11"
# ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
# USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
# USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
# ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"

# Load profile (since we need xprofile to work with TTY and DMs anything
# sourced on a non-default in Xsession will be sourced in xprofile)
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.xprofile"; do
	if [ -f "$file" ]; then
		echo "Loading profile from $file"
		. "$file"
	fi
done

# # Load resources
# for file in "/etc/X11/Xresources" "$HOME/.Xresources"; do
#     if [ -f "$file" ]; then
#         echo "Loading resource: $file"
#         xrdb -merge "$file"
#     fi
# done

# # Load keymaps
# for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
#     if [ -f "$file" ]; then
#         echo "Loading keymap: $file"
#         setxkbmap `cat "$file"`
#         XKB_IN_USE=yes
#     fi
# done

# # Load xmodmap if not using XKB
# if [ -z "$XKB_IN_USE" ]; then
#     for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
#         if [ -f "$file" ]; then
#            echo "Loading modmap: $file"
#            xmodmap "$file"
#         fi
#     done
# fi

# unset XKB_IN_USE

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
	for script in $xinitdir/*; do
		echo "Loading xinit script $script"
		if [ -x "$script" -a ! -d "$script" ]; then
			. "$script"
		fi
	done
fi

# Run user xsession shell script
script="$HOME/.xsession"
if [ -x "$script" -a ! -d "$script" ]; then
	echo "Loading xsession script $script"
	. "$script"
fi

# Here Qtile is kept as default
session=${1:-qtile}

case $session in
i3 | i3wm) exec i3 ;;
kde) exec startplasma-x11 ;;
xfce | xfce4) exec startxfce4 ;;
qtile) exec qtile start ;;
# No known session, try to run it as command
*) exec $1 ;; # exec $@
esac
